// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/maintainv1/maintainer.proto

package maintainv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MaintainerService_ListRules_FullMethodName           = "/muxcore.library.maintainer.v1.MaintainerService/ListRules"
	MaintainerService_GetRule_FullMethodName             = "/muxcore.library.maintainer.v1.MaintainerService/GetRule"
	MaintainerService_UpsertRule_FullMethodName          = "/muxcore.library.maintainer.v1.MaintainerService/UpsertRule"
	MaintainerService_DeleteRule_FullMethodName          = "/muxcore.library.maintainer.v1.MaintainerService/DeleteRule"
	MaintainerService_PreviewRule_FullMethodName         = "/muxcore.library.maintainer.v1.MaintainerService/PreviewRule"
	MaintainerService_ListCollections_FullMethodName     = "/muxcore.library.maintainer.v1.MaintainerService/ListCollections"
	MaintainerService_UpsertCollection_FullMethodName    = "/muxcore.library.maintainer.v1.MaintainerService/UpsertCollection"
	MaintainerService_DeleteCollection_FullMethodName    = "/muxcore.library.maintainer.v1.MaintainerService/DeleteCollection"
	MaintainerService_ListCandidates_FullMethodName      = "/muxcore.library.maintainer.v1.MaintainerService/ListCandidates"
	MaintainerService_GetCandidate_FullMethodName        = "/muxcore.library.maintainer.v1.MaintainerService/GetCandidate"
	MaintainerService_ApproveCandidate_FullMethodName    = "/muxcore.library.maintainer.v1.MaintainerService/ApproveCandidate"
	MaintainerService_PostponeCandidate_FullMethodName   = "/muxcore.library.maintainer.v1.MaintainerService/PostponeCandidate"
	MaintainerService_CancelCandidate_FullMethodName     = "/muxcore.library.maintainer.v1.MaintainerService/CancelCandidate"
	MaintainerService_ListProtections_FullMethodName     = "/muxcore.library.maintainer.v1.MaintainerService/ListProtections"
	MaintainerService_UpsertProtection_FullMethodName    = "/muxcore.library.maintainer.v1.MaintainerService/UpsertProtection"
	MaintainerService_DeleteProtection_FullMethodName    = "/muxcore.library.maintainer.v1.MaintainerService/DeleteProtection"
	MaintainerService_ScanNow_FullMethodName             = "/muxcore.library.maintainer.v1.MaintainerService/ScanNow"
	MaintainerService_ActNow_FullMethodName              = "/muxcore.library.maintainer.v1.MaintainerService/ActNow"
	MaintainerService_ListRuns_FullMethodName            = "/muxcore.library.maintainer.v1.MaintainerService/ListRuns"
	MaintainerService_ListExclusionLists_FullMethodName  = "/muxcore.library.maintainer.v1.MaintainerService/ListExclusionLists"
	MaintainerService_UpsertExclusionList_FullMethodName = "/muxcore.library.maintainer.v1.MaintainerService/UpsertExclusionList"
	MaintainerService_DeleteExclusionList_FullMethodName = "/muxcore.library.maintainer.v1.MaintainerService/DeleteExclusionList"
	MaintainerService_SyncExclusionLists_FullMethodName  = "/muxcore.library.maintainer.v1.MaintainerService/SyncExclusionLists"
	MaintainerService_CheckImportBlocked_FullMethodName  = "/muxcore.library.maintainer.v1.MaintainerService/CheckImportBlocked"
	MaintainerService_ExportRules_FullMethodName         = "/muxcore.library.maintainer.v1.MaintainerService/ExportRules"
	MaintainerService_ImportRules_FullMethodName         = "/muxcore.library.maintainer.v1.MaintainerService/ImportRules"
	MaintainerService_GetStorageMetrics_FullMethodName   = "/muxcore.library.maintainer.v1.MaintainerService/GetStorageMetrics"
	MaintainerService_ListPlaybackUsers_FullMethodName   = "/muxcore.library.maintainer.v1.MaintainerService/ListPlaybackUsers"
)

// MaintainerServiceClient is the client API for MaintainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaintainerServiceClient interface {
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error)
	UpsertRule(ctx context.Context, in *UpsertRuleRequest, opts ...grpc.CallOption) (*UpsertRuleResponse, error)
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error)
	PreviewRule(ctx context.Context, in *PreviewRuleRequest, opts ...grpc.CallOption) (*PreviewRuleResponse, error)
	ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	UpsertCollection(ctx context.Context, in *UpsertCollectionRequest, opts ...grpc.CallOption) (*UpsertCollectionResponse, error)
	DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error)
	ListCandidates(ctx context.Context, in *ListCandidatesRequest, opts ...grpc.CallOption) (*ListCandidatesResponse, error)
	GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error)
	ApproveCandidate(ctx context.Context, in *ApproveCandidateRequest, opts ...grpc.CallOption) (*ApproveCandidateResponse, error)
	PostponeCandidate(ctx context.Context, in *PostponeCandidateRequest, opts ...grpc.CallOption) (*PostponeCandidateResponse, error)
	CancelCandidate(ctx context.Context, in *CancelCandidateRequest, opts ...grpc.CallOption) (*CancelCandidateResponse, error)
	ListProtections(ctx context.Context, in *ListProtectionsRequest, opts ...grpc.CallOption) (*ListProtectionsResponse, error)
	UpsertProtection(ctx context.Context, in *UpsertProtectionRequest, opts ...grpc.CallOption) (*UpsertProtectionResponse, error)
	DeleteProtection(ctx context.Context, in *DeleteProtectionRequest, opts ...grpc.CallOption) (*DeleteProtectionResponse, error)
	ScanNow(ctx context.Context, in *ScanNowRequest, opts ...grpc.CallOption) (*ScanNowResponse, error)
	ActNow(ctx context.Context, in *ActNowRequest, opts ...grpc.CallOption) (*ActNowResponse, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	ListExclusionLists(ctx context.Context, in *ListExclusionListsRequest, opts ...grpc.CallOption) (*ListExclusionListsResponse, error)
	UpsertExclusionList(ctx context.Context, in *UpsertExclusionListRequest, opts ...grpc.CallOption) (*UpsertExclusionListResponse, error)
	DeleteExclusionList(ctx context.Context, in *DeleteExclusionListRequest, opts ...grpc.CallOption) (*DeleteExclusionListResponse, error)
	SyncExclusionLists(ctx context.Context, in *SyncExclusionListsRequest, opts ...grpc.CallOption) (*SyncExclusionListsResponse, error)
	CheckImportBlocked(ctx context.Context, in *CheckImportBlockedRequest, opts ...grpc.CallOption) (*CheckImportBlockedResponse, error)
	ExportRules(ctx context.Context, in *ExportRulesRequest, opts ...grpc.CallOption) (*ExportRulesResponse, error)
	ImportRules(ctx context.Context, in *ImportRulesRequest, opts ...grpc.CallOption) (*ImportRulesResponse, error)
	GetStorageMetrics(ctx context.Context, in *GetStorageMetricsRequest, opts ...grpc.CallOption) (*GetStorageMetricsResponse, error)
	ListPlaybackUsers(ctx context.Context, in *ListPlaybackUsersRequest, opts ...grpc.CallOption) (*ListPlaybackUsersResponse, error)
}

type maintainerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaintainerServiceClient(cc grpc.ClientConnInterface) MaintainerServiceClient {
	return &maintainerServiceClient{cc}
}

func (c *maintainerServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleResponse)
	err := c.cc.Invoke(ctx, MaintainerService_GetRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) UpsertRule(ctx context.Context, in *UpsertRuleRequest, opts ...grpc.CallOption) (*UpsertRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRuleResponse)
	err := c.cc.Invoke(ctx, MaintainerService_UpsertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRuleResponse)
	err := c.cc.Invoke(ctx, MaintainerService_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) PreviewRule(ctx context.Context, in *PreviewRuleRequest, opts ...grpc.CallOption) (*PreviewRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewRuleResponse)
	err := c.cc.Invoke(ctx, MaintainerService_PreviewRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) UpsertCollection(ctx context.Context, in *UpsertCollectionRequest, opts ...grpc.CallOption) (*UpsertCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertCollectionResponse)
	err := c.cc.Invoke(ctx, MaintainerService_UpsertCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCollectionResponse)
	err := c.cc.Invoke(ctx, MaintainerService_DeleteCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ListCandidates(ctx context.Context, in *ListCandidatesRequest, opts ...grpc.CallOption) (*ListCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCandidatesResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ListCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidateResponse)
	err := c.cc.Invoke(ctx, MaintainerService_GetCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ApproveCandidate(ctx context.Context, in *ApproveCandidateRequest, opts ...grpc.CallOption) (*ApproveCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveCandidateResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ApproveCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) PostponeCandidate(ctx context.Context, in *PostponeCandidateRequest, opts ...grpc.CallOption) (*PostponeCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostponeCandidateResponse)
	err := c.cc.Invoke(ctx, MaintainerService_PostponeCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) CancelCandidate(ctx context.Context, in *CancelCandidateRequest, opts ...grpc.CallOption) (*CancelCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCandidateResponse)
	err := c.cc.Invoke(ctx, MaintainerService_CancelCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ListProtections(ctx context.Context, in *ListProtectionsRequest, opts ...grpc.CallOption) (*ListProtectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProtectionsResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ListProtections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) UpsertProtection(ctx context.Context, in *UpsertProtectionRequest, opts ...grpc.CallOption) (*UpsertProtectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertProtectionResponse)
	err := c.cc.Invoke(ctx, MaintainerService_UpsertProtection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) DeleteProtection(ctx context.Context, in *DeleteProtectionRequest, opts ...grpc.CallOption) (*DeleteProtectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProtectionResponse)
	err := c.cc.Invoke(ctx, MaintainerService_DeleteProtection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ScanNow(ctx context.Context, in *ScanNowRequest, opts ...grpc.CallOption) (*ScanNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanNowResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ScanNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ActNow(ctx context.Context, in *ActNowRequest, opts ...grpc.CallOption) (*ActNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActNowResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ActNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ListExclusionLists(ctx context.Context, in *ListExclusionListsRequest, opts ...grpc.CallOption) (*ListExclusionListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExclusionListsResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ListExclusionLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) UpsertExclusionList(ctx context.Context, in *UpsertExclusionListRequest, opts ...grpc.CallOption) (*UpsertExclusionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertExclusionListResponse)
	err := c.cc.Invoke(ctx, MaintainerService_UpsertExclusionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) DeleteExclusionList(ctx context.Context, in *DeleteExclusionListRequest, opts ...grpc.CallOption) (*DeleteExclusionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExclusionListResponse)
	err := c.cc.Invoke(ctx, MaintainerService_DeleteExclusionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) SyncExclusionLists(ctx context.Context, in *SyncExclusionListsRequest, opts ...grpc.CallOption) (*SyncExclusionListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncExclusionListsResponse)
	err := c.cc.Invoke(ctx, MaintainerService_SyncExclusionLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) CheckImportBlocked(ctx context.Context, in *CheckImportBlockedRequest, opts ...grpc.CallOption) (*CheckImportBlockedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckImportBlockedResponse)
	err := c.cc.Invoke(ctx, MaintainerService_CheckImportBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ExportRules(ctx context.Context, in *ExportRulesRequest, opts ...grpc.CallOption) (*ExportRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRulesResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ExportRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ImportRules(ctx context.Context, in *ImportRulesRequest, opts ...grpc.CallOption) (*ImportRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportRulesResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ImportRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) GetStorageMetrics(ctx context.Context, in *GetStorageMetricsRequest, opts ...grpc.CallOption) (*GetStorageMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageMetricsResponse)
	err := c.cc.Invoke(ctx, MaintainerService_GetStorageMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerServiceClient) ListPlaybackUsers(ctx context.Context, in *ListPlaybackUsersRequest, opts ...grpc.CallOption) (*ListPlaybackUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlaybackUsersResponse)
	err := c.cc.Invoke(ctx, MaintainerService_ListPlaybackUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaintainerServiceServer is the server API for MaintainerService service.
// All implementations must embed UnimplementedMaintainerServiceServer
// for forward compatibility.
type MaintainerServiceServer interface {
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error)
	UpsertRule(context.Context, *UpsertRuleRequest) (*UpsertRuleResponse, error)
	DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
	PreviewRule(context.Context, *PreviewRuleRequest) (*PreviewRuleResponse, error)
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	UpsertCollection(context.Context, *UpsertCollectionRequest) (*UpsertCollectionResponse, error)
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error)
	ListCandidates(context.Context, *ListCandidatesRequest) (*ListCandidatesResponse, error)
	GetCandidate(context.Context, *GetCandidateRequest) (*GetCandidateResponse, error)
	ApproveCandidate(context.Context, *ApproveCandidateRequest) (*ApproveCandidateResponse, error)
	PostponeCandidate(context.Context, *PostponeCandidateRequest) (*PostponeCandidateResponse, error)
	CancelCandidate(context.Context, *CancelCandidateRequest) (*CancelCandidateResponse, error)
	ListProtections(context.Context, *ListProtectionsRequest) (*ListProtectionsResponse, error)
	UpsertProtection(context.Context, *UpsertProtectionRequest) (*UpsertProtectionResponse, error)
	DeleteProtection(context.Context, *DeleteProtectionRequest) (*DeleteProtectionResponse, error)
	ScanNow(context.Context, *ScanNowRequest) (*ScanNowResponse, error)
	ActNow(context.Context, *ActNowRequest) (*ActNowResponse, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	ListExclusionLists(context.Context, *ListExclusionListsRequest) (*ListExclusionListsResponse, error)
	UpsertExclusionList(context.Context, *UpsertExclusionListRequest) (*UpsertExclusionListResponse, error)
	DeleteExclusionList(context.Context, *DeleteExclusionListRequest) (*DeleteExclusionListResponse, error)
	SyncExclusionLists(context.Context, *SyncExclusionListsRequest) (*SyncExclusionListsResponse, error)
	CheckImportBlocked(context.Context, *CheckImportBlockedRequest) (*CheckImportBlockedResponse, error)
	ExportRules(context.Context, *ExportRulesRequest) (*ExportRulesResponse, error)
	ImportRules(context.Context, *ImportRulesRequest) (*ImportRulesResponse, error)
	GetStorageMetrics(context.Context, *GetStorageMetricsRequest) (*GetStorageMetricsResponse, error)
	ListPlaybackUsers(context.Context, *ListPlaybackUsersRequest) (*ListPlaybackUsersResponse, error)
	mustEmbedUnimplementedMaintainerServiceServer()
}

// UnimplementedMaintainerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaintainerServiceServer struct{}

func (UnimplementedMaintainerServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedMaintainerServiceServer) GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRule not implemented")
}
func (UnimplementedMaintainerServiceServer) UpsertRule(context.Context, *UpsertRuleRequest) (*UpsertRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertRule not implemented")
}
func (UnimplementedMaintainerServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedMaintainerServiceServer) PreviewRule(context.Context, *PreviewRuleRequest) (*PreviewRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewRule not implemented")
}
func (UnimplementedMaintainerServiceServer) ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedMaintainerServiceServer) UpsertCollection(context.Context, *UpsertCollectionRequest) (*UpsertCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCollection not implemented")
}
func (UnimplementedMaintainerServiceServer) DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollection not implemented")
}
func (UnimplementedMaintainerServiceServer) ListCandidates(context.Context, *ListCandidatesRequest) (*ListCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCandidates not implemented")
}
func (UnimplementedMaintainerServiceServer) GetCandidate(context.Context, *GetCandidateRequest) (*GetCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedMaintainerServiceServer) ApproveCandidate(context.Context, *ApproveCandidateRequest) (*ApproveCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveCandidate not implemented")
}
func (UnimplementedMaintainerServiceServer) PostponeCandidate(context.Context, *PostponeCandidateRequest) (*PostponeCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostponeCandidate not implemented")
}
func (UnimplementedMaintainerServiceServer) CancelCandidate(context.Context, *CancelCandidateRequest) (*CancelCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCandidate not implemented")
}
func (UnimplementedMaintainerServiceServer) ListProtections(context.Context, *ListProtectionsRequest) (*ListProtectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProtections not implemented")
}
func (UnimplementedMaintainerServiceServer) UpsertProtection(context.Context, *UpsertProtectionRequest) (*UpsertProtectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertProtection not implemented")
}
func (UnimplementedMaintainerServiceServer) DeleteProtection(context.Context, *DeleteProtectionRequest) (*DeleteProtectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProtection not implemented")
}
func (UnimplementedMaintainerServiceServer) ScanNow(context.Context, *ScanNowRequest) (*ScanNowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanNow not implemented")
}
func (UnimplementedMaintainerServiceServer) ActNow(context.Context, *ActNowRequest) (*ActNowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActNow not implemented")
}
func (UnimplementedMaintainerServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedMaintainerServiceServer) ListExclusionLists(context.Context, *ListExclusionListsRequest) (*ListExclusionListsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExclusionLists not implemented")
}
func (UnimplementedMaintainerServiceServer) UpsertExclusionList(context.Context, *UpsertExclusionListRequest) (*UpsertExclusionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertExclusionList not implemented")
}
func (UnimplementedMaintainerServiceServer) DeleteExclusionList(context.Context, *DeleteExclusionListRequest) (*DeleteExclusionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExclusionList not implemented")
}
func (UnimplementedMaintainerServiceServer) SyncExclusionLists(context.Context, *SyncExclusionListsRequest) (*SyncExclusionListsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncExclusionLists not implemented")
}
func (UnimplementedMaintainerServiceServer) CheckImportBlocked(context.Context, *CheckImportBlockedRequest) (*CheckImportBlockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckImportBlocked not implemented")
}
func (UnimplementedMaintainerServiceServer) ExportRules(context.Context, *ExportRulesRequest) (*ExportRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportRules not implemented")
}
func (UnimplementedMaintainerServiceServer) ImportRules(context.Context, *ImportRulesRequest) (*ImportRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportRules not implemented")
}
func (UnimplementedMaintainerServiceServer) GetStorageMetrics(context.Context, *GetStorageMetricsRequest) (*GetStorageMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorageMetrics not implemented")
}
func (UnimplementedMaintainerServiceServer) ListPlaybackUsers(context.Context, *ListPlaybackUsersRequest) (*ListPlaybackUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlaybackUsers not implemented")
}
func (UnimplementedMaintainerServiceServer) mustEmbedUnimplementedMaintainerServiceServer() {}
func (UnimplementedMaintainerServiceServer) testEmbeddedByValue()                           {}

// UnsafeMaintainerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaintainerServiceServer will
// result in compilation errors.
type UnsafeMaintainerServiceServer interface {
	mustEmbedUnimplementedMaintainerServiceServer()
}

func RegisterMaintainerServiceServer(s grpc.ServiceRegistrar, srv MaintainerServiceServer) {
	// If the following call pancis, it indicates UnimplementedMaintainerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaintainerService_ServiceDesc, srv)
}

func _MaintainerService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_GetRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).GetRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_GetRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).GetRule(ctx, req.(*GetRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_UpsertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).UpsertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_UpsertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).UpsertRule(ctx, req.(*UpsertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_PreviewRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).PreviewRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_PreviewRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).PreviewRule(ctx, req.(*PreviewRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_UpsertCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).UpsertCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_UpsertCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).UpsertCollection(ctx, req.(*UpsertCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_DeleteCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).DeleteCollection(ctx, req.(*DeleteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ListCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ListCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ListCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ListCandidates(ctx, req.(*ListCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_GetCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).GetCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_GetCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).GetCandidate(ctx, req.(*GetCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ApproveCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ApproveCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ApproveCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ApproveCandidate(ctx, req.(*ApproveCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_PostponeCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostponeCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).PostponeCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_PostponeCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).PostponeCandidate(ctx, req.(*PostponeCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_CancelCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).CancelCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_CancelCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).CancelCandidate(ctx, req.(*CancelCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ListProtections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProtectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ListProtections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ListProtections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ListProtections(ctx, req.(*ListProtectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_UpsertProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).UpsertProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_UpsertProtection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).UpsertProtection(ctx, req.(*UpsertProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_DeleteProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).DeleteProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_DeleteProtection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).DeleteProtection(ctx, req.(*DeleteProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ScanNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ScanNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ScanNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ScanNow(ctx, req.(*ScanNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ActNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ActNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ActNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ActNow(ctx, req.(*ActNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ListExclusionLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExclusionListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ListExclusionLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ListExclusionLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ListExclusionLists(ctx, req.(*ListExclusionListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_UpsertExclusionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertExclusionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).UpsertExclusionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_UpsertExclusionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).UpsertExclusionList(ctx, req.(*UpsertExclusionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_DeleteExclusionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExclusionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).DeleteExclusionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_DeleteExclusionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).DeleteExclusionList(ctx, req.(*DeleteExclusionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_SyncExclusionLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncExclusionListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).SyncExclusionLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_SyncExclusionLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).SyncExclusionLists(ctx, req.(*SyncExclusionListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_CheckImportBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckImportBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).CheckImportBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_CheckImportBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).CheckImportBlocked(ctx, req.(*CheckImportBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ExportRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ExportRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ExportRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ExportRules(ctx, req.(*ExportRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ImportRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ImportRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ImportRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ImportRules(ctx, req.(*ImportRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_GetStorageMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).GetStorageMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_GetStorageMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).GetStorageMetrics(ctx, req.(*GetStorageMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintainerService_ListPlaybackUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlaybackUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServiceServer).ListPlaybackUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintainerService_ListPlaybackUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServiceServer).ListPlaybackUsers(ctx, req.(*ListPlaybackUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MaintainerService_ServiceDesc is the grpc.ServiceDesc for MaintainerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaintainerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.library.maintainer.v1.MaintainerService",
	HandlerType: (*MaintainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _MaintainerService_ListRules_Handler,
		},
		{
			MethodName: "GetRule",
			Handler:    _MaintainerService_GetRule_Handler,
		},
		{
			MethodName: "UpsertRule",
			Handler:    _MaintainerService_UpsertRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _MaintainerService_DeleteRule_Handler,
		},
		{
			MethodName: "PreviewRule",
			Handler:    _MaintainerService_PreviewRule_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _MaintainerService_ListCollections_Handler,
		},
		{
			MethodName: "UpsertCollection",
			Handler:    _MaintainerService_UpsertCollection_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _MaintainerService_DeleteCollection_Handler,
		},
		{
			MethodName: "ListCandidates",
			Handler:    _MaintainerService_ListCandidates_Handler,
		},
		{
			MethodName: "GetCandidate",
			Handler:    _MaintainerService_GetCandidate_Handler,
		},
		{
			MethodName: "ApproveCandidate",
			Handler:    _MaintainerService_ApproveCandidate_Handler,
		},
		{
			MethodName: "PostponeCandidate",
			Handler:    _MaintainerService_PostponeCandidate_Handler,
		},
		{
			MethodName: "CancelCandidate",
			Handler:    _MaintainerService_CancelCandidate_Handler,
		},
		{
			MethodName: "ListProtections",
			Handler:    _MaintainerService_ListProtections_Handler,
		},
		{
			MethodName: "UpsertProtection",
			Handler:    _MaintainerService_UpsertProtection_Handler,
		},
		{
			MethodName: "DeleteProtection",
			Handler:    _MaintainerService_DeleteProtection_Handler,
		},
		{
			MethodName: "ScanNow",
			Handler:    _MaintainerService_ScanNow_Handler,
		},
		{
			MethodName: "ActNow",
			Handler:    _MaintainerService_ActNow_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _MaintainerService_ListRuns_Handler,
		},
		{
			MethodName: "ListExclusionLists",
			Handler:    _MaintainerService_ListExclusionLists_Handler,
		},
		{
			MethodName: "UpsertExclusionList",
			Handler:    _MaintainerService_UpsertExclusionList_Handler,
		},
		{
			MethodName: "DeleteExclusionList",
			Handler:    _MaintainerService_DeleteExclusionList_Handler,
		},
		{
			MethodName: "SyncExclusionLists",
			Handler:    _MaintainerService_SyncExclusionLists_Handler,
		},
		{
			MethodName: "CheckImportBlocked",
			Handler:    _MaintainerService_CheckImportBlocked_Handler,
		},
		{
			MethodName: "ExportRules",
			Handler:    _MaintainerService_ExportRules_Handler,
		},
		{
			MethodName: "ImportRules",
			Handler:    _MaintainerService_ImportRules_Handler,
		},
		{
			MethodName: "GetStorageMetrics",
			Handler:    _MaintainerService_GetStorageMetrics_Handler,
		},
		{
			MethodName: "ListPlaybackUsers",
			Handler:    _MaintainerService_ListPlaybackUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/maintainv1/maintainer.proto",
}
